apiVersion: v1
kind: Namespace
metadata:
  name: cilsy-staging

---

apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: cilsy-staging
  name: compro-staging
  labels:
    app: compro-staging
spec:
  replicas: 1
  selector:
    matchLabels:
      app: compro-staging
  template:
    metadata:
      labels:
        app: compro-staging
    spec:
      containers:
      - name: compro-staging
        image: hansenfernando/cilsylandingpage-staging:latest
        ports:
        - containerPort: 80
---

kind: Service
apiVersion: v1
metadata:
  namespace: cilsy-staging
  name: compro-svc-staging
spec:
  selector:
    app: compro-staging
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80

---

apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  namespace: cilsy-staging
  name: compro-ingress-staging
  annotations:
     kubernetes.io/ingress.class: "nginx"
     nginx.ingress.kubernetes.io/affinity: "cookie"
     nginx.ingress.kubernetes.io/session-cookie-name: "compro-staging-cookie"
     nginx.ingress.kubernetes.io/session-cookie-expires: "86400"
     nginx.ingress.kubernetes.io/session-cookie-max-age: "86400"
     nginx.ingress.kubernetes.io/ssl-redirect: "false"
     nginx.ingress.kubernetes.io/affinity-mode: persistent
     nginx.ingress.kubernetes.io/session-cookie-hash: sha1
spec:
  rules:
  - host: staging-landingpage.hansenfernando.xyz      
    http:
      paths:
        - backend:
           serviceName: compro-svc-staging
           servicePort: 80
